apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
    name: policies
spec:
    stages:
        - name: production
          cluster:
            repository: https://github.com/Bhanu88/aks-gitops.git
            name: cluster1
          resources:
            path: cluster/global/policies
          targetNamespace: policies
